[profile.default]
  ast = true
  auto_detect_solc = true
  build_info = true
  extra_output = ["storageLayout"]
  ffi = true
  gas_limit = "18446744073709551615"
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  src = "src"
  via-ir = true

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true
